### ISSUE TITLE
nfs to pst: MIME-Version: 1.0

### ISSUE THREAD

**Issue by berom1** [adb014/nsf2x#16]
First, thanks a lot for this great tool.

I'm trying to migrate my emails from Lotus notes 9.0.1FP2 to Office 365 (Outlook 2016).

Using the x86 version of your software, I got the conversion done. 
However, after migration, all of my emails don't have a sender and receiver, the first line of each email is "MIME-Version: 1.0" and the content is HTML shown as text with banners.

Is there an option I need to configure?

**Comment by adb014** [comment]
At the moment I don't know how to treat this issue. I tried to fix it in version v1.3.5 but the problem is the access to the MimeToMAPI function in o365 seems to be giving the unconverted files you are seeing. At this point the only thing I can suggest is using NSF2X with a full installation of Office rather than o365
