### ISSUE TITLE
Encrypted messages

### ISSUE THREAD

**Issue by UdoBonjernoor** [adb014/nsf2x#19]
When converting an archief , the job holds on every encrypted message in the archive. Is het possible to make an option that skips encrypted messages ?

**Comment by jdeniau35** [comment]
What you can do is a simple ibm nsf app that scans all mailfiles, detects encrypted mails and if there are encrypted mail send a memo to the end user that contains code to unencrypt mails. Due to domino/notes security only the pivate key of the user (in id file) can decrypt the mails. once done you can migrate with nsf2x

**Comment by adb014** [comment]
NSF2X is not supposed to "hold" for encrypted Notes messages. Normally two outcomes are possible. 1/ You have the associated user key to the encrypted Notes message. In that case NSF2X is supposed to unencrypt the message and allow you to reencrypt the message with your private mail certificat in the windows certificat store, or optionally remove the encrytion completely. 2/ If you don't have the Notes user key associated with the encrytion, NSF2X will fail to unencrypt the message, signal the problem and continue.

jdeniau35 solution seems a reasonable workaround for your problem. So I'm flagging this as answered and closing it
